spring:
  application:
    name: ribbon-consumer
server:
  port: 8804
  servlet:
    context-path: /ribbon

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance-id:${spring.application.instance-id:${random.value}}}
    hostname: ribbon
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8701/register/eureka/,http://peer2:8702/register/eureka/


