spring:
  application:
    name: eureka-consumer
server:
  port: 8803
  servlet:
    context-path: /consumer

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance-id:${spring.application.instance-id:${random.value}}}
    hostname: producer
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8801/register/eureka/


